version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-user
    ports:
      - "32770:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
