quarkus:
  smallrye-openapi:
    enable: true
    ui:
      path: /swagger-ui   # Optional: Customize the endpoint for the Swagger UI
    path: /openapi        # Optional: Customize the JSON endpoint for the OpenAPI specification
  datasource:
    devservices:
      port: 5432